=== twiederk/d20Framework/src/main/java/com/d20charactersheet/framework/boc/service/exportimport/d20cs_characters.dtd
<?xml version="1.0" encoding="UTF-8"?>
    <!ELEMENT characters (character+)>
    <!ATTLIST characters version CDATA #FIXED "1">
    <!ATTLIST characters gamesystem CDATA #REQUIRED>

    <!ELEMENT character (appearance,attributes,combat,saves,money,notes,attacks,skills,feats,spells,equipment)>

    <!-- Appearance -->
    <!ELEMENT appearance (name,player,race,sex,classlevels,alignment,xppoints,xptableid)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT player (#PCDATA)>
    <!ELEMENT race (#PCDATA)>
    <!ELEMENT sex (#PCDATA)>
    <!ELEMENT classlevels (classlevel)>
    <!ELEMENT classlevel (class,level,classabilities)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT level (#PCDATA)>
    <!ELEMENT classabilities (classability*)>
    <!ELEMENT classability (#PCDATA)>
    <!ATTLIST classability name CDATA #REQUIRED>
    <!ATTLIST classability owned CDATA #REQUIRED>
    <!ELEMENT alignment (#PCDATA)>
    <!ELEMENT xppoints (#PCDATA)>
    <!ELEMENT xptableid (#PCDATA)>

    <!-- Attributes -->
    <!ELEMENT attributes (attribute+)>
    <!ELEMENT attribute (#PCDATA)>
    <!ATTLIST attribute name CDATA #REQUIRED>
    <!ATTLIST attribute value CDATA #REQUIRED>

    <!-- Combat -->
    <!ELEMENT combat (hitpoints,maxhitpoints,armormod,initiativemod,cmbmod,cmdmod)>
    <!ELEMENT hitpoints (#PCDATA)>
    <!ELEMENT maxhitpoints (#PCDATA)>
    <!ELEMENT armormod (#PCDATA)>
    <!ELEMENT initiativemod (#PCDATA)>
    <!ELEMENT cmbmod (#PCDATA)>
    <!ELEMENT cmdmod (#PCDATA)>

    <!-- Saves -->
    <!ELEMENT saves (fortifymod,reflexmod,willmod)>
    <!ELEMENT fortifymod (#PCDATA)>
    <!ELEMENT reflexmod (#PCDATA)>
    <!ELEMENT willmod (#PCDATA)>

    <!-- Money -->
    <!ELEMENT money (platinum,gold,silver,copper)>
    <!ELEMENT platinum (#PCDATA)>
    <!ELEMENT gold (#PCDATA)>
    <!ELEMENT silver (#PCDATA)>
    <!ELEMENT copper (#PCDATA)>

    <!-- Notes -->
    <!ELEMENT notes (note*)>
    <!ELEMENT note (date,text)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT text (#PCDATA)>

    <!-- Attacks -->
    <!ELEMENT attacks (attack*)>
    <!ELEMENT attack (name,description,attackwield,attackweapon,attackbonusmod,damagebonusmod)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT attackwield (#PCDATA)>
    <!ELEMENT attackweapon (#PCDATA)>
    <!ELEMENT attackbonusmod (#PCDATA)>
    <!ELEMENT damagebonusmod (#PCDATA)>

    <!-- Skills -->
    <!ELEMENT skills (skill*)>
    <!ELEMENT skill (name,rank,skillmod)>
    <!ELEMENT rank (#PCDATA)>
    <!ELEMENT skillmod (#PCDATA)>

    <!-- Feats -->
    <!ELEMENT feats (feat*)>
    <!ELEMENT feat (name,category)>
    <!ELEMENT category (#PCDATA)>

    <!-- Spells -->
    <!ELEMENT spells (spell*)>
    <!ELEMENT spell (name)>

    <!-- Equipment -->
    <!ELEMENT equipment (weapons,armors,goods)>
    <!ELEMENT weapons (weapon*)>
    <!ELEMENT weapon (name,number)>
    <!ELEMENT armors (armor*)>
    <!ELEMENT armor (name,number)>
    <!ELEMENT goods (good*)>
    <!ELEMENT good (name,number)>
    <!ELEMENT number (#PCDATA)>

=== twiederk/d20Framework/src/test/resources/exportimport/d20cs_characters_v1_unit_test_Diba.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE characters PUBLIC
    "http://www.d20CharacterSheet.com/xml/v1/d20cs_characters.dtd"
    "file:/C:/LocalData/Projekte/DnDFramework/Technik/workspace/d20Framework/src/main/java/com/d20charactersheet/framework/boc/service/exportimport/d20cs_characters.dtd" >
<characters gamesystem="Dungeons &amp; Dragons v.3.5" version="1"><character><appearance><name>Belvador the Summoner</name><player>Torsten</player><race>High Elf</race><sex>MALE</sex><classlevels><classlevel><class>Wizard</class><level>5</level><classabilities><classability name="Familiar" owned="true"/><classability name="Spells - Wizard" owned="true"/><classability name="Bonus Languages - Wizard" owned="true"/><classability name="Scribe Scroll" owned="true"/><classability name="Bonus Feats - Wizard" owned="true"/><classability name="Spellbooks" owned="true"/><classability name="School Specialization" owned="true"/><classability name="School Specialization - Conjuration" owned="true"/><classability name="School Specialization - Abjuration" owned="false"/><classability name="School Specialization - Divination" owned="false"/><classability name="School Specialization - Enchantment" owned="false"/><classability name="School Specialization - Evocation" owned="false"/><classability name="School Specialization - Illusion" owned="false"/><classability name="School Specialization - Necromancy" owned="false"/><classability name="School Specialization - Transmutation" owned="false"/><classability name="School Specialization - Universal" owned="false"/></classabilities></classlevel></classlevels><alignment>CHAOTIC_GOOD</alignment><xppoints>13129</xppoints><xptableid>1</xptableid></appearance><attributes><attribute name="STRENGTH" value="11"/><attribute name="DEXTERITY" value="18"/><attribute name="CONSTITUTION" value="17"/><attribute name="INTELLIGENCE" value="18"/><attribute name="WISDOM" value="11"/><attribute name="CHARISMA" value="15"/></attributes><combat><hitpoints>26</hitpoints><maxhitpoints>26</maxhitpoints><armormod>0</armormod><initiativemod>0</initiativemod><cmbmod>0</cmbmod><cmdmod>0</cmdmod></combat><saves><fortifymod>0</fortifymod><reflexmod>0</reflexmod><willmod>0</willmod></saves><money><platinum>1</platinum><gold>2</gold><silver>3</silver><copper>4</copper></money><notes><note><date>2013-04-13 15:30</date><text>My test note!</text></note></notes><attacks><attack><name>Quarterstaff</name><description>My good old quaterstaff</description><attackwield>TWO_HANDED</attackwield><attackweapon>Quarterstaff</attackweapon><attackbonusmod>0</attackbonusmod><damagebonusmod>0</damagebonusmod></attack><attack><name>Crossbow, light</name><description/><attackwield>ONE_HAND</attackwield><attackweapon>Crossbow, light</attackweapon><attackbonusmod>0</attackbonusmod><damagebonusmod>0</damagebonusmod></attack><attack><name>Silver Dagger</name><description>Use against lycanthropes</description><attackwield>ONE_HAND</attackwield><attackweapon>Silver Dagger</attackweapon><attackbonusmod>0</attackbonusmod><damagebonusmod>0</damagebonusmod></attack></attacks><skills><skill><name>Concentration</name><rank>8.0</rank><skillmod>0</skillmod></skill><skill><name>Knowledge (arcana)</name><rank>7.0</rank><skillmod>0</skillmod></skill><skill><name>Knowledge (history)</name><rank>7.0</rank><skillmod>0</skillmod></skill><skill><name>Knowledge (religion)</name><rank>2.0</rank><skillmod>2</skillmod></skill><skill><name>Listen</name><rank>0.0</rank><skillmod>2</skillmod></skill><skill><name>Search</name><rank>4.0</rank><skillmod>2</skillmod></skill><skill><name>Spellcraft</name><rank>8.0</rank><skillmod>2</skillmod></skill><skill><name>Spot</name><rank>4.0</rank><skillmod>2</skillmod></skill><skill><name>Survival</name><rank>0.0</rank><skillmod>2</skillmod></skill><skill><name>Use Magic Device</name><rank>0.0</rank><skillmod>2</skillmod></skill></skills><feats><feat><name>Augment Summoning</name><category/></feat><feat><name>Extend Spell</name><category/></feat><feat><name>Spell Focus</name><category>Summoning</category></feat></feats><spells><spell><name>Arcane Mark</name></spell><spell><name>Dancing Lights</name></spell><spell><name>Daze</name></spell><spell><name>Detect Magic</name></spell><spell><name>Detect Poison</name></spell><spell><name>Flare</name></spell><spell><name>Light</name></spell><spell><name>Mage Hand</name></spell><spell><name>Mending</name></spell><spell><name>Open/Close</name></spell><spell><name>Prestidigitation</name></spell><spell><name>Ray of Frost</name></spell><spell><name>Read Magic</name></spell><spell><name>Resistance</name></spell><spell><name>Charm Person</name></spell><spell><name>Mage Armor</name></spell><spell><name>Magic Missile</name></spell><spell><name>Mount</name></spell><spell><name>Protection from Evil</name></spell><spell><name>Shield</name></spell><spell><name>Sleep</name></spell><spell><name>Summon Monster I</name></spell><spell><name>Unseen Servant</name></spell><spell><name>Acid Arrow</name></spell><spell><name>Flaming Sphere</name></spell><spell><name>Knock</name></spell><spell><name>Spider Climb</name></spell><spell><name>Levitate</name></spell><spell><name>Summon Monster II</name></spell><spell><name>Summon Monster III</name></spell><spell><name>Lightning Bolt</name></spell></spells><equipment><weapons><weapon><name>Quarterstaff</name><number>1</number></weapon><weapon><name>Crossbow, light</name><number>1</number></weapon><weapon><name>Bolts, crossbow (10)</name><number>2</number></weapon></weapons><armors><armor><name>Padded</name><number>2</number></armor></armors><goods><good><name>Backpack</name><number>1</number></good><good><name>Waterskin</name><number>1</number></good><good><name>Trail Rations (per Day)</name><number>10</number></good><good><name>Bedroll</name><number>1</number></good><good><name>Flint and Steel</name><number>1</number></good><good><name>Candle</name><number>8</number></good><good><name>Scroll Case</name><number>1</number></good><good><name>Parchment (Sheet)</name><number>3</number></good><good><name>Vial of Ink</name><number>1</number></good><good><name>Inkpen</name><number>1</number></good><good><name>Spellbook</name><number>1</number></good><good><name>Outfit Noble</name><number>1</number></good><good><name>Bullseye Lantern</name><number>1</number></good><good><name>Flask of Oil</name><number>2</number></good><good><name>Torch</name><number>3</number></good><good><name>Antitoxin (vial)</name><number>1</number></good><good><name>Horse, light</name><number>1</number></good><good><name>Saddle, riding</name><number>1</number></good><good><name>Saddlebags</name><number>1</number></good></goods></equipment></character></characters>
