=== twiederk/d20Framework/src/main/java/com/d20charactersheet/framework/boc/service/exportimport/d20cs_equipment.dtd
<?xml version="1.0" encoding="UTF-8"?>
    <!ELEMENT equipment (weapons,armors,goods)>
    <!ATTLIST equipment version CDATA #FIXED "1">
    <!ATTLIST equipment gamesystem CDATA #REQUIRED>

    <!ELEMENT weapons (weapon*)>
    <!ELEMENT armors (armor*)>
    <!ELEMENT goods (good*)>

    <!-- weapon -->
    <!ELEMENT weapon (name,cost,weight,quality,description,type,damage,critical,combat,encumbrance,category,enhancement,family,rangeincrement)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT cost (#PCDATA)>
    <!ELEMENT weight (#PCDATA)>
    <!ELEMENT quality (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT damage (#PCDATA)>
    <!ATTLIST damage numberofdice CDATA #REQUIRED>
    <!ATTLIST damage die CDATA #REQUIRED>
    <!ELEMENT critical (#PCDATA)>
    <!ATTLIST critical hit CDATA #REQUIRED>
    <!ATTLIST critical multiplier CDATA #REQUIRED>
    <!ELEMENT combat (#PCDATA)>
    <!ELEMENT encumbrance (#PCDATA)>
    <!ELEMENT category (#PCDATA)>
    <!ELEMENT enhancement (#PCDATA)>
    <!ELEMENT family (#PCDATA)>
    <!ELEMENT rangeincrement (#PCDATA)>

    <!-- armor -->
    <!ELEMENT armor (name,cost,weight,quality,description,type,bonus,penalty)>
    <!ELEMENT bonus (#PCDATA)>
    <!ELEMENT penalty (#PCDATA)>

    <!-- good -->
    <!ELEMENT good (name,cost,weight,quality,description,type)>

=== twiederk/d20Framework/src/test/resources/exportimport/d20cs_equipment_v1_unit_test_Home.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE equipment PUBLIC "http://www.d20CharacterSheet.com/xml/v1/d20cs_equipment.dtd" "file:/E:/projects/DnDFramework/Technik/workspace/d20Framework/src/main/java/com/d20charactersheet/framework/boc/service/exportimport/d20cs_equipment.dtd"><equipment gamesystem="Dungeons &amp; Dragons v.3.5" version="1"><weapons><weapon><name>Gauntlet</name><cost>2.0</cost><weight>1.0</weight><quality>NORMAL</quality><description>This metal glove lets you deal lethal damage rather than nonlethal damage with unarmed strikes. A strike with a gauntlet is otherwise considered an unarmed attack. The cost and weight given are for a single gauntlet. Medium and heavy armors (except breastplate) come with gauntlets.</description><type>SIMPLE</type><damage die="D3" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>LIGHT_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Unarmed strike</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Dagger</name><cost>2.0</cost><weight>1.0</weight><quality>NORMAL</quality><description>You get a +2 bonus on Sleight of Hand checks made to conceal a dagger on your body (see the Sleight of Hand skill)</description><type>SIMPLE</type><damage die="D4" numberofdice="1"/><critical hit="19" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>LIGHT_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Dagger</family><rangeincrement>10</rangeincrement></weapon><weapon><name>Dagger, punching</name><cost>2.0</cost><weight>1.0</weight><quality>NORMAL</quality><description/><type>SIMPLE</type><damage die="D4" numberofdice="1"/><critical hit="20" multiplier="3"/><combat>MELEE_WEAPON</combat><encumbrance>LIGHT_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Dagger</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Gauntlet, spiked</name><cost>5.0</cost><weight>1.0</weight><quality>NORMAL</quality><description>Your opponent cannot use a disarm action to disarm you of spiked gauntlets. The cost and weight given are for a single gauntlet. An attack with a spiked gauntlet is considered an armed attack.</description><type>SIMPLE</type><damage die="D4" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>LIGHT_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Unarmed strike</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Mace, light</name><cost>5.0</cost><weight>4.0</weight><quality>NORMAL</quality><description/><type>SIMPLE</type><damage die="D6" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>LIGHT_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Mace, light</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Sickle</name><cost>6.0</cost><weight>2.0</weight><quality>NORMAL</quality><description>A sickle can be used to make trip attacks. If you are tripped during your own trip attempt, you can drop the sickle to avoid being tripped.</description><type>SIMPLE</type><damage die="D6" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>LIGHT_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Sickle</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Club</name><cost>0.0</cost><weight>3.0</weight><quality>NORMAL</quality><description/><type>SIMPLE</type><damage die="D6" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>ONE_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Club</family><rangeincrement>10</rangeincrement></weapon><weapon><name>Mace, heavy</name><cost>12.0</cost><weight>8.0</weight><quality>NORMAL</quality><description/><type>SIMPLE</type><damage die="D8" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>ONE_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Mace, heavy</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Morningstar</name><cost>8.0</cost><weight>6.0</weight><quality>NORMAL</quality><description/><type>SIMPLE</type><damage die="D8" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>ONE_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Morningstar</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Shortspear</name><cost>1.0</cost><weight>3.0</weight><quality>NORMAL</quality><description>A shortspear is small enough to wield one-handed. It may also be thrown.</description><type>SIMPLE</type><damage die="D6" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>ONE_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Shortspear</family><rangeincrement>20</rangeincrement></weapon><weapon><name>Longspear</name><cost>5.0</cost><weight>9.0</weight><quality>NORMAL</quality><description>A longspear has reach. You can strike opponents 10 feet away with it, but you can''t use it against an adjacent foe. If you use a ready action to set a longspear against a charge, you deal double damage on a successful hit against a charging character.</description><type>SIMPLE</type><damage die="D8" numberofdice="1"/><critical hit="20" multiplier="3"/><combat>MELEE_WEAPON</combat><encumbrance>TWO_HANDED</encumbrance><category>REACH_WEAPON</category><enhancement>0</enhancement><family>Longspear</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Quarterstaff</name><cost>0.0</cost><weight>4.0</weight><quality>NORMAL</quality><description>A quarterstaff is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. A creature wielding a quarterstaff in one hand can''t use it as a double weapon - only one end of the weapon can be used in any given round. The quarterstaff is a special monk weapon. This designation gives a monk wielding a quarterstaff special options.</description><type>SIMPLE</type><damage die="D6" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>MELEE_WEAPON</combat><encumbrance>TWO_HANDED</encumbrance><category>DOUBLE_WEAPON</category><enhancement>0</enhancement><family>Quarterstaff</family><rangeincrement>0</rangeincrement></weapon><weapon><name>Spear</name><cost>2.0</cost><weight>6.0</weight><quality>NORMAL</quality><description>A spear can be thrown. If you use a ready action to set a spear against a charge, you deal double damage on a successful hit against a charging character.</description><type>SIMPLE</type><damage die="D8" numberofdice="1"/><critical hit="20" multiplier="3"/><combat>MELEE_WEAPON</combat><encumbrance>TWO_HANDED</encumbrance><category>NORMAL_WEAPON</category><enhancement>0</enhancement><family>Spear</family><rangeincrement>20</rangeincrement></weapon><weapon><name>Crossbow, heavy</name><cost>50.0</cost><weight>8.0</weight><quality>NORMAL</quality><description>You draw a heavy crossbow back by turning a small winch. Loading a heavy crossbow is a full-round action that provokes attacks of opportunity. Normally, operating a heavy crossbow requires two hands. However, you can shoot, but not load, a heavy crossbow with one hand at a -4 penalty on attack rolls. You can shoot a heavy crossbow with each hand, but you take a penalty on attack rolls as if attacking with two one-handed weapons. This penalty is cumulative with the penalty for one-handed firing.</description><type>SIMPLE</type><damage die="D10" numberofdice="1"/><critical hit="19" multiplier="2"/><combat>RANGED_WEAPON</combat><encumbrance>ONE_HANDED</encumbrance><category>PROJECTILE_WEAPON</category><enhancement>0</enhancement><family>Crossbow, heavy</family><rangeincrement>120</rangeincrement></weapon><weapon><name>Crossbow, light</name><cost>35.0</cost><weight>4.0</weight><quality>NORMAL</quality><description>You draw a light crossbow back by pulling a lever. Loading a light crossbow is a move action that provokes attacks of opportunity. Normally, operating a light crossbow requires two hands. However, you can shoot, but not load, a light crossbow with one hand at a -2 penalty on attack rolls. You can shoot a light crossbow with each hand, but you take a penalty on attack rolls as if attacking with two light weapons. This penalty is cumulative with the penalty for one-handed firing.</description><type>SIMPLE</type><damage die="D8" numberofdice="1"/><critical hit="19" multiplier="2"/><combat>RANGED_WEAPON</combat><encumbrance>ONE_HANDED</encumbrance><category>PROJECTILE_WEAPON</category><enhancement>0</enhancement><family>Crossbow, light</family><rangeincrement>80</rangeincrement></weapon><weapon><name>Dart</name><cost>5.0</cost><weight>0.5</weight><quality>NORMAL</quality><description/><type>SIMPLE</type><damage die="D4" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>RANGED_WEAPON</combat><encumbrance>LIGHT_HANDED</encumbrance><category>THROWN_WEAPON</category><enhancement>0</enhancement><family>Dart</family><rangeincrement>20</rangeincrement></weapon><weapon><name>Javelin</name><cost>1.0</cost><weight>2.0</weight><quality>NORMAL</quality><description>Since it is not designed for melee, you are treated as nonproficient with it and take a -4 penalty on attack rolls if you use a javelin as a melee weapon.</description><type>SIMPLE</type><damage die="D6" numberofdice="1"/><critical hit="20" multiplier="2"/><combat>RANGED_WEAPON</combat><encumbrance>ONE_HANDED</encumbrance><category>THROWN_WEAPON</category><enhancement>0</enhancemen
